/** Display-only decimal strings. Financial arithmetic and chain reads belong to the adapter. */
export type Amount = string;
export type OfferMode = 'public' | 'private';
export type OfferStatus = 'valid' | 'expired' | 'stale' | 'unfunded' | 'cancelled' | 'encrypted';
export interface Offer { id: string; claimId: string; maker: string; makerAddress?: string; teamOperated: boolean; net?: Amount; gross?: Amount; fee?: Amount; deadline: number; status: OfferStatus; mode: OfferMode; reason?: string; recordUrl?: string; }
export interface Claim { id: string; title: string; source: string; sourceAddress?: string; owner: string; isOwner: boolean; expected: Amount; pending: Amount; claimable: Amount; collected: Amount; withdrawn: Amount; walletWithdrawn?: Amount; cost?: Amount; realized?: Amount; residualCost?: Amount; timing: string; status: 'pending' | 'collectible' | 'partial' | 'exhausted' | 'loss'; epoch: string; depletion: string; recovery: string; sourceRisk: string; explorerUrl?: string; history: { label: string; detail: string; amount?: Amount; txUrl?: string }[]; }
export interface AppData { environment: 'preview' | 'local' | 'fuji' | 'unavailable'; chainName: string; chainId?: number; wallet?: string; wrongNetwork: boolean; balance?: Amount; claims: Claim[]; offers: Offer[]; loading: boolean; error?: string; updatedAt?: number; services: { name: string; status: 'connected' | 'unavailable' | 'preview'; detail: string }[]; privateKeyStatus: 'available' | 'locked' | 'missing'; }
export interface TransactionResult { status: 'confirmed' | 'pending' | 'replaced'; message: string; hash?: string; explorerUrl?: string; }
export interface AppActions { connect(): Promise<void>; switchNetwork(): Promise<void>; refresh(): Promise<void>; faucet(): Promise<TransactionResult>; originate(): Promise<TransactionResult>; requestOffers(claimId: string, mode: OfferMode): Promise<TransactionResult>; acceptOffer(offerId: string): Promise<TransactionResult>; collect(claimId: string): Promise<TransactionResult>; withdraw(claimId: string): Promise<TransactionResult>; makeOffer(claimId: string, net: string, mode?: OfferMode): Promise<TransactionResult>; cancelOffer(offerId: string): Promise<TransactionResult>; unlockPrivateOffers(claimId: string): Promise<void>; }
