import type { AppData, AppActions } from './model';
export const previewData: AppData = {
 environment:'preview', chainName:'Avalanche Fuji · preview data', wrongNetwork:false, loading:false, privateKeyStatus:'missing',
 services:[{name:'Avalanche',status:'preview',detail:'Illustrative claim data; no transactions.'},{name:'Arkiv',status:'preview',detail:'Illustrative offer discovery; no live query.'},{name:'Swarm',status:'preview',detail:'Illustrative records; no live retrieval.'}],
 claims:[{id:'1042',title:'USDC withdrawal',source:'EXIT Test Withdrawal Vault',owner:'0x71C7…2f8A',isOwner:true,expected:'10000',pending:'6000',claimable:'4000',collected:'0',withdrawn:'0',timing:'Two controlled installments',status:'collectible',epoch:'0',depletion:'0',recovery:'Ownership continues for supported later recoveries.',sourceRisk:'Team-controlled test source. Installments and adverse payouts are controlled for demonstration. Test USDC has no monetary value.',history:[{label:'Withdrawal originated',detail:'10,000 test USDC backed in test vault',amount:'10000'}]},
 {id:'1041',title:'Residual USDC rights',source:'EXIT Test Withdrawal Vault',owner:'0xA4e9…901B',isOwner:false,expected:'6000',pending:'6000',claimable:'0',collected:'0',withdrawn:'4000',walletWithdrawn:'4000',cost:'9960',residualCost:'5960',timing:'Final controlled installment',status:'partial',epoch:'1',depletion:'1',recovery:'Current owner retains supported recovery rights.',sourceRisk:'Test source with controlled timing. Residual proceeds are estimates; loss is possible.',history:[{label:'Purchased by maker A',detail:'Exact net paid to original seller',amount:'9960'},{label:'First installment withdrawn',detail:'Cash paid to maker A; old full-claim offers are stale',amount:'4000'}]},
 {id:'1040',title:'Adverse payout scenario',source:'EXIT Test Withdrawal Vault',owner:'0x4B82…cc19',isOwner:false,expected:'5700',pending:'0',claimable:'5700',collected:'0',withdrawn:'0',cost:'5985',timing:'Available to collect',status:'loss',epoch:'2',depletion:'1',recovery:'Later recoveries belong to the current owner.',sourceRisk:'Separate loss example: 5,985 paid for an expected 6,000; actual proceeds reduced to 5,700. No reimbursement.',history:[{label:'Residual rights acquired',detail:'Buyer B paid 5,985',amount:'5985'},{label:'Adverse outcome recorded',detail:'Actual remaining payout is 5,700',amount:'5700'}]}],
 offers:[{id:'offer-a',claimId:'1042',maker:'EXIT maker A',teamOperated:true,net:'9960',gross:'9960',fee:'0',deadline:Date.now()+900000,status:'valid',mode:'public'}, {id:'offer-b',claimId:'1042',maker:'EXIT maker B',teamOperated:true,net:'9940',gross:'9940',fee:'0',deadline:Date.now()+720000,status:'valid',mode:'public'}, {id:'offer-c',claimId:'1042',maker:'EXIT maker C',teamOperated:true,net:'9900',gross:'9900',fee:'0',deadline:Date.now()+600000,status:'valid',mode:'public'},{id:'offer-stale',claimId:'1041',maker:'EXIT maker C',teamOperated:true,net:'9960',gross:'9960',fee:'0',deadline:Date.now()+900000,status:'stale',reason:'Includes the 4,000 already withdrawn. Request an offer for residual rights.',mode:'public'}, {id:'offer-residual',claimId:'1041',maker:'EXIT maker B',teamOperated:true,net:'5985',gross:'5985',fee:'0',deadline:Date.now()+900000,status:'valid',mode:'public'}]
};
const unavailable = async ():Promise<never> => { throw new Error('This is a design preview. Open the connected application to perform real transactions.'); };
export const previewActions: AppActions = {connect:unavailable,switchNetwork:unavailable,refresh:async()=>{},faucet:unavailable,originate:unavailable,requestOffers:unavailable,acceptOffer:unavailable,collect:unavailable,withdraw:unavailable,makeOffer:unavailable,cancelOffer:unavailable,unlockPrivateOffers:unavailable};
export const unavailableData: AppData = {environment:'unavailable',chainName:'No deployment configured',wrongNetwork:false,claims:[],offers:[],loading:false,error:'The application has no connected data adapter. Configure the deployment and start the API to read real claims. Preview data is available only through the explicit design-preview link.',services:[],privateKeyStatus:'missing'};
