import { writeFile, mkdir } from "node:fs/promises";
import { artifact } from "../packages/runtime/chain";
await mkdir("packages/shared", { recursive: true });
for (const name of [
  "ExitMarket",
  "TestWithdrawalVault",
  "TestUSDC",
  "OfferKeyRegistry",
]) {
  const a = await artifact(name);
  await writeFile(
    `packages/shared/${name}.ts`,
    `// Generated by npm run abi; do not hand edit.\nexport const ${name}Abi = ${JSON.stringify(a.abi, null, 2)} as const;\n`,
  );
}
